import os
import json
from Machine_Learning.config import BASE_DIR

class CropAdvisor:
    _defaults = None
    
    @classmethod
    def load_defaults(cls):
        """
        Loads the crop ideal averages generated by the EDA script.
        """
        if cls._defaults is None:
            defaults_path = os.path.join(BASE_DIR, 'Machine_Learning', 'crop_defaults.json')
            if not os.path.exists(defaults_path):
                return {}
            with open(defaults_path, 'r') as f:
                cls._defaults = json.load(f)
        return cls._defaults

    @classmethod
    def get_crops_list(cls):
        """
        Returns a sorted list of all available crops in the dataset.
        """
        defaults = cls.load_defaults()
        return sorted(list(defaults.keys())) if defaults else []

    @classmethod
    def analyze_and_optimize(cls, target_crop, actual_inputs):
        """
        Compares actual inputs to the target crop's ideal average values and returns
        optimization advice for each parameter.
        """
        defaults = cls.load_defaults()
        if not defaults or target_crop not in defaults:
            return {
                'status': 'error',
                'message': f"No ideal benchmarks found for crop '{target_crop}'. Run EDA script first."
            }
            
        ideal = defaults[target_crop]
        advice = {}
        overall_status = "Optimal"
        deviations_count = 0
        
        # 1. Nutrient Advice (N, P, K)
        for nutrient in ['N', 'P', 'K']:
            act_val = float(actual_inputs[nutrient])
            idl_val = float(ideal[nutrient])
            diff = act_val - idl_val
            pct_diff = (diff / idl_val) * 100 if idl_val > 0 else 0
            
            nutrient_name = 'Nitrogen (N)' if nutrient == 'N' else ('Phosphorus (P)' if nutrient == 'P' else 'Potassium (K)')
            
            if pct_diff < -15:
                # Deficient
                deviations_count += 1
                status = "Deficient"
                severity = "danger"
                offset_desc = f"Deficit of {abs(diff):.1f} mg/kg (-{abs(pct_diff):.0f}%)"
                if nutrient == 'N':
                    action = "Apply Nitrogen-rich fertilizers like Urea, Ammonium Nitrate, or organic blood meal/manure."
                elif nutrient == 'P':
                    action = "Apply Bone meal, Rock phosphate, or Superphosphate fertilizers to stimulate root systems."
                else:
                    action = "Apply Muriate of Potash, Potassium Sulfate, or organic wood ash to enhance crop resilience."
            elif pct_diff > 15:
                # Excess
                deviations_count += 1
                status = "Excessive"
                severity = "warning"
                offset_desc = f"Surplus of {diff:.1f} mg/kg (+{pct_diff:.0f}%)"
                if nutrient == 'N':
                    action = "Avoid nitrogen application. Add carbonaceous organic matter (like straw or sawdust) to tie up excess nitrogen."
                elif nutrient == 'P':
                    action = "Avoid phosphate fertilizer. Excess phosphorus can lock out micronutrients like zinc and iron; apply iron chelates if needed."
                else:
                    action = "Avoid potash. Flush soil with clean water if drainage allows, and harvest crops that accumulate potassium (e.g. leafy greens)."
            else:
                status = "Optimal"
                severity = "success"
                offset_desc = f"Balanced (within 15% of ideal {idl_val:.1f} mg/kg)"
                action = "Maintain current soil management practices."
                
            advice[nutrient] = {
                'name': nutrient_name,
                'ideal': idl_val,
                'actual': act_val,
                'status': status,
                'severity': severity,
                'offset_desc': offset_desc,
                'action_recommendation': action
            }

        # 2. pH Advice
        act_ph = float(actual_inputs['ph'])
        idl_ph = float(ideal['ph'])
        ph_diff = act_ph - idl_ph
        
        if ph_diff < -0.6:
            deviations_count += 1
            ph_status = "Acidic (Low)"
            ph_severity = "danger"
            ph_action = "Incorporate agricultural lime (calcium carbonate) or dolomite lime to raise pH. Wood ash can also be used in small quantities."
        elif ph_diff > 0.6:
            deviations_count += 1
            ph_status = "Alkaline (High)"
            ph_severity = "warning"
            ph_action = "Apply elemental sulfur, iron sulfate, or organic mulches (like peat moss or pine needles) to acidify and lower the soil pH."
        else:
            ph_status = "Optimal"
            ph_severity = "success"
            ph_action = "Your soil pH is in the optimal range. Avoid heavy applications of strongly acidic or basic soil amendments."
            
        advice['ph'] = {
            'name': 'Soil pH',
            'ideal': idl_ph,
            'actual': act_ph,
            'status': ph_status,
            'severity': ph_severity,
            'offset_desc': f"Offset of {ph_diff:+.2f} points (Ideal: {idl_ph:.2f})",
            'action_recommendation': ph_action
        }

        # 3. Environment Advice (Water / Rainfall)
        act_rain = float(actual_inputs['rainfall'])
        idl_rain = float(ideal['rainfall'])
        rain_diff = act_rain - idl_rain
        rain_pct = (rain_diff / idl_rain) * 100 if idl_rain > 0 else 0
        
        if rain_pct < -20:
            deviations_count += 1
            rain_status = "Insufficient"
            rain_severity = "danger"
            rain_action = f"Water deficit of {abs(rain_diff):.1f} mm. Implement supplemental drip irrigation or sprinkler systems. Use heavy organic mulching to conserve soil moisture."
        elif rain_pct > 20:
            deviations_count += 1
            rain_status = "Surplus"
            rain_severity = "warning"
            rain_action = f"Water surplus of {rain_diff:.1f} mm. Ensure proper surface and sub-surface drainage channels to avoid waterlogging and root rot. Plant on raised beds if possible."
        else:
            rain_status = "Optimal"
            rain_severity = "success"
            rain_action = "Rainfall matches requirements. Ensure soil organic matter is maintained to preserve water-holding capacity."
            
        advice['rainfall'] = {
            'name': 'Rainfall (Water)',
            'ideal': idl_rain,
            'actual': act_rain,
            'status': rain_status,
            'severity': rain_severity,
            'offset_desc': f"Offset of {rain_diff:+.1f} mm (Ideal: {idl_rain:.1f} mm)",
            'action_recommendation': rain_action
        }

        # 4. Temperature & Humidity Overview
        act_temp = float(actual_inputs['temperature'])
        idl_temp = float(ideal['temperature'])
        act_hum = float(actual_inputs['humidity'])
        idl_hum = float(ideal['humidity'])
        
        temp_status = "Normal" if abs(act_temp - idl_temp) < 4 else ("Too Cold" if act_temp < idl_temp else "Too Hot")
        hum_status = "Normal" if abs(act_hum - idl_hum) < 15 else ("Too Dry" if act_hum < idl_hum else "Too Humid")
        
        advice['climate'] = {
            'temperature': {
                'actual': act_temp,
                'ideal': idl_temp,
                'status': temp_status,
                'action_recommendation': "For high temperatures, use shade nets and mulching. For cold, greenhouses or row covers help retain heat." if temp_status != "Normal" else "Temperature is suitable for growth."
            },
            'humidity': {
                'actual': act_hum,
                'ideal': idl_hum,
                'status': hum_status,
                'action_recommendation': "If too dry, increase irrigation and misting. If too humid, increase planting spacing to facilitate ventilation and reduce fungal risks." if hum_status != "Normal" else "Humidity levels are ideal."
            }
        }
        
        if deviations_count >= 3:
            overall_status = "Sub-Optimal (Needs Correction)"
        elif deviations_count >= 1:
            overall_status = "Mild Deviations (Monitor/Adjust)"
        else:
            overall_status = "Excellent Matching (No adjustments needed)"
            
        return {
            'status': 'success',
            'target_crop': target_crop,
            'overall_status': overall_status,
            'advice': advice,
            'deviations_count': deviations_count
        }
